# Generated by Django 3.2.9 on 2024-09-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PICIIP_SWL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotrequests',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
