# Generated by Django 3.2.9 on 2024-09-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PICIIP_SWL', '0002_alter_plotrequests_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotrequests',
            name='landuse_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='plotrequests',
            name='kml_path',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plotrequests',
            name='map_document',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
