# Generated by Django 3.2.9 on 2024-09-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PICIIP_SWL', '0003_auto_20240912_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotrequests',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='plotrequests',
            name='kml_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plotrequests',
            name='map_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plotrequests',
            name='submitted_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
