# Generated by Django 3.2.9 on 2024-09-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PICIIP_SWL', '0004_auto_20240912_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotrequests',
            name='request_status',
            field=models.CharField(blank=True, choices=[('In Process', 'In Process'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='In Process', max_length=25, null=True),
        ),
    ]
