# Generated by Django 3.2.9 on 2024-09-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PICIIP_SWL', '0005_plotrequests_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotrequests',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plotrequests',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='plotrequests',
            name='request_status',
            field=models.CharField(blank=True, choices=[('In Process', 'In Process'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='In Process', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plotrequests',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
