# Generated by Django 5.1.3 on 2024-11-05 09:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PICIIP_SWL', '0006_auto_20240912_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedHousingSchemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_name', models.CharField(blank=True, max_length=50, null=True)),
                ('area_arc', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'approved_housing_schemes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrickKiln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('building_a', models.CharField(blank=True, max_length=50, null=True)),
                ('b_height', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('row', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('lu_upd', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'brick_kiln',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='plotrequests',
            name='kmlArea',
            field=models.CharField(blank=True, db_column='kml_area', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='plotrequests',
            name='cnic',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
