# Generated by Django 5.1.3 on 2024-11-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PICIIP_SWL', '0007_approvedhousingschemes_brickkiln_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_table', models.CharField(max_length=255)),
                ('increament_decrement', models.IntegerField()),
                ('area_in_acre', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'action_logs',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='plotrequests',
            name='Email',
            field=models.CharField(blank=True, db_column='Email', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plotrequests',
            name='SubZone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='plotrequests',
            name='abuttingRoad',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='plotrequests',
            name='cnic_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plotrequests',
            name='existingsituation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='plotrequests',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plotrequests',
            name='revenue_document_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
